version: '3'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./storage/logs/nginx:/var/log/nginx
            - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
            - "443:443" 
        links:
            - app
        networks:
            - backend             
    app:
        container_name: laravel-vue-crud
        build: 
            context: ./
            dockerfile: docker/app.dockerfile
        volumes:
            - ./:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql" 
        links:
            - mysql
        networks:
            - backend       
    mysql:
        image: mysql:8
        ports:
            - "33061:3306"
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=laravel-vue-crud"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=secret"
        networks:
            - backend

volumes:
    dbdata:

networks:
  backend:
    driver: "bridge"
